/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.devops.simpleform.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SimpleFrom service. Represents a row in the &quot;do_simpleform&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.devops.simpleform.model.impl.SimpleFromModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.devops.simpleform.model.impl.SimpleFromImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SimpleFrom
 * @see com.fds.devops.simpleform.model.impl.SimpleFromImpl
 * @see com.fds.devops.simpleform.model.impl.SimpleFromModelImpl
 * @generated
 */
@ProviderType
public interface SimpleFromModel extends BaseModel<SimpleFrom>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a simple from model instance should use the {@link SimpleFrom} interface instead.
	 */

	/**
	 * Returns the primary key of this simple from.
	 *
	 * @return the primary key of this simple from
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this simple from.
	 *
	 * @param primaryKey the primary key of this simple from
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this simple from.
	 *
	 * @return the uuid of this simple from
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this simple from.
	 *
	 * @param uuid the uuid of this simple from
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the form ID of this simple from.
	 *
	 * @return the form ID of this simple from
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this simple from.
	 *
	 * @param formId the form ID of this simple from
	 */
	public void setFormId(long formId);

	/**
	 * Returns the group ID of this simple from.
	 *
	 * @return the group ID of this simple from
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this simple from.
	 *
	 * @param groupId the group ID of this simple from
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this simple from.
	 *
	 * @return the company ID of this simple from
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this simple from.
	 *
	 * @param companyId the company ID of this simple from
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this simple from.
	 *
	 * @return the user ID of this simple from
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this simple from.
	 *
	 * @param userId the user ID of this simple from
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this simple from.
	 *
	 * @return the user uuid of this simple from
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this simple from.
	 *
	 * @param userUuid the user uuid of this simple from
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this simple from.
	 *
	 * @return the user name of this simple from
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this simple from.
	 *
	 * @param userName the user name of this simple from
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this simple from.
	 *
	 * @return the create date of this simple from
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this simple from.
	 *
	 * @param createDate the create date of this simple from
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this simple from.
	 *
	 * @return the modified date of this simple from
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this simple from.
	 *
	 * @param modifiedDate the modified date of this simple from
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the full name of this simple from.
	 *
	 * @return the full name of this simple from
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this simple from.
	 *
	 * @param fullName the full name of this simple from
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the birthday of this simple from.
	 *
	 * @return the birthday of this simple from
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this simple from.
	 *
	 * @param birthday the birthday of this simple from
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the gender of this simple from.
	 *
	 * @return the gender of this simple from
	 */
	public int getGender();

	/**
	 * Sets the gender of this simple from.
	 *
	 * @param gender the gender of this simple from
	 */
	public void setGender(int gender);

	/**
	 * Returns the email of this simple from.
	 *
	 * @return the email of this simple from
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this simple from.
	 *
	 * @param email the email of this simple from
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this simple from.
	 *
	 * @return the address of this simple from
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this simple from.
	 *
	 * @param address the address of this simple from
	 */
	public void setAddress(String address);

	/**
	 * Returns the short desciption of this simple from.
	 *
	 * @return the short desciption of this simple from
	 */
	@AutoEscape
	public String getShortDesciption();

	/**
	 * Sets the short desciption of this simple from.
	 *
	 * @param shortDesciption the short desciption of this simple from
	 */
	public void setShortDesciption(String shortDesciption);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SimpleFrom simpleFrom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SimpleFrom> toCacheModel();

	@Override
	public SimpleFrom toEscapedModel();

	@Override
	public SimpleFrom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}